
name: deploying static website


on:

  push:
    branches: [ master ]
 
  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            node-version: [8.x, 10.x, 12.x]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: install surge
        run: npm install -g surge
      
      - name : run surge
        run : surge ./ test.surge.sh ${{secrets.SURGE_TOKEN}}
